### ISSUE TITLE
Add server/performance section

### ISSUE THREAD

**Issue by kubaceg** [punkstar/magentotherightway.com#13]
I think it will be nice to add section about server/performance. We can insert there another useful informations such as:
- for database server use Percona instead of MySQL,
- for better performance use PHP version >= 5.4,
- install some cache for PHP (apc, opcache),
- remember to disable Xdebug on production servers,
- use nginx + php-fpm instead of Apache2,
- remember to enabling Magento cache on production enviroment.

I think these tips will be very useful for other developers. What you thik guys?

**Comment by punkstar** [comment]
+1

**Comment by punkstar** [comment]
PR #14.
